#ifndef GENGODB_DIALECT_GRAPH_OPS
#define GENGODB_DIALECT_GRAPH_OPS

include "mlir/IR/OpBase.td"
include "mlir/IR/EnumAttr.td"
include "mlir/IR/AttrTypeBase.td"
include "mlir/Interfaces/SideEffectInterfaces.td"
include "mlir/Interfaces/ControlFlowInterfaces.td"
include "mlir/Interfaces/InferTypeOpInterface.td"
include "mlir/IR/SymbolInterfaces.td"
include "gengodb/compiler/Dialect/Graph/GraphDialect.td"

//===----------------------------------------------------------------------===//
// Ops
//===----------------------------------------------------------------------===//

class Graph_Op<string mnemonic, list<Trait> traits = []> : Op<Graph_Dialect, mnemonic, traits> {
    let hasCustomAssemblyFormat = 1;
}

def CreateGraphOp : Graph_Op<"subop.create_graph", [Pure,StateCreator]> {
    let summary = "create new graph";
    let arguments = (ins I64Attr : $numNodes, I64Attr : $numRels, I64Attr : $numProps);
    let results = (outs Graph : $res);
    let assemblyFormat = [{ `{` `nodes` `=` $numNodes `,` `relations` `=` $numRels `,` `properties` `=` $numProps `}` `:` type($res) attr-dict }];
}

def Graph_BuiltinGraph_BASIC : I64EnumAttrCase<"standard", 0>;
def Graph_BuiltinGraph_PAGERANK : I64EnumAttrCase<"pagerank", 1>;
def Graph_BuiltinGraph_PROPERTYGRAPH : I64EnumAttrCase<"propertygraph", 2>;
def Graph_BuiltinGraph : I64EnumAttr<"BuiltinGraphAttr", "",
        [Graph_BuiltinGraph_BASIC,Graph_BuiltinGraph_PAGERANK,Graph_BuiltinGraph_PROPERTYGRAPH]> {
    let cppNamespace = "::gengodb::compiler::dialect::graph";
}
def CreateBuiltinGraphOp : Graph_Op<"subop.create_builtin_graph", [Pure,StateCreator]> {
    let summary = "create builtin graph";
    let arguments = (ins Graph_BuiltinGraph : $graphId);
    let results = (outs Graph : $res);
    let assemblyFormat = [{ `{` `builtin` `=` $graphId `}` `:` type($res) attr-dict }];
}

def GetExternalGraphOp : Graph_Op<"subop.get_external_graph", [Pure,StateCreator]> {
    let summary = "get external graph";
    let arguments = (ins StrAttr : $name, StrAttr : $graphId);
    let results = (outs Graph : $res);
    let assemblyFormat = [{ `{` `name` `=`  $name `,` `id` `=` $graphId `}` `:` type($res) attr-dict }];
}

def ScanGraphOp : Graph_Op<"subop.scan_graph", [Pure,SubOperator,DeclareOpInterfaceMethods<StateUsingSubOperator>]> {
    let summary = "scan state (sequentially)";
    let arguments = (ins AnyType : $graph, ColumnDefAttr: $nodeSet, ColumnDefAttr: $edgeSet);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{ $graph `:` type($graph) custom<CustDef>($nodeSet) `,` custom<CustDef>($edgeSet) attr-dict }];
    let extraClassDeclaration = [{
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

def ScanNodeSetOp : Graph_Op<"subop.scan_node_set", [Pure,SubOperator,ReferenceProducer,DeclareOpInterfaceMethods<StateUsingSubOperator>]> {
    let summary = "scan state (sequentially)";
    let arguments = (ins AnyType : $node_set, ColumnDefAttr: $ref);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{ $node_set `:` type($node_set) custom<CustDef>($ref) attr-dict }];
    let extraClassDeclaration = [{
        lingodb::compiler::dialect::tuples::ColumnDefAttr getProducedReference(){ return getRef(); }
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}
def ScanEdgeSetOp : Graph_Op<"subop.scan_edge_set", [Pure,SubOperator,ReferenceProducer,DeclareOpInterfaceMethods<StateUsingSubOperator>]> {
    let summary = "scan state (sequentially)";
    let arguments = (ins AnyType : $edge_set, ColumnDefAttr: $ref);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{ $edge_set `:` type($edge_set) custom<CustDef>($ref) attr-dict }];
    let extraClassDeclaration = [{
        lingodb::compiler::dialect::tuples::ColumnDefAttr getProducedReference(){ return getRef(); }
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

def NodeCountOp : Graph_Op<"node_count", [Pure,SubOperator,ReferenceProducer,DeclareOpInterfaceMethods<StateUsingSubOperator>]> {
    let summary = "graph node count";

    let arguments = (ins TupleStream : $stream, Graph : $graph, ColumnDefAttr:$ref);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{  $stream `,` $graph `->` custom<CustDef>($ref) `:` type($graph) attr-dict }];
    let extraClassDeclaration = [{
        lingodb::compiler::dialect::tuples::ColumnDefAttr getProducedReference(){ return getRef(); }
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

def EdgeCountOp : Graph_Op<"edge_count", [Pure,SubOperator,ReferenceProducer,DeclareOpInterfaceMethods<StateUsingSubOperator>]> {
    let summary = "graph edge count";

    let arguments = (ins TupleStream : $stream, Graph : $graph, ColumnDefAttr:$ref);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{  $stream `,` $graph `->` custom<CustDef>($ref) `:` type($graph) attr-dict }];
    let extraClassDeclaration = [{
        lingodb::compiler::dialect::tuples::ColumnDefAttr getProducedReference(){ return getRef(); }
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

def NodeDegreeOp : Graph_Op<"node_degree", [Pure,SubOperator,ReferenceProducer,DeclareOpInterfaceMethods<StateUsingSubOperator>]> {
    let summary = "node degree op";

    let arguments = (ins TupleStream : $stream, Graph : $graph, ColumnDefAttr:$ref, StrAttr:$dir);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{  $stream `,` $graph `[` $dir `]` `->` custom<CustDef>($ref) `:` type($graph) attr-dict }];
    let extraClassDeclaration = [{
        lingodb::compiler::dialect::tuples::ColumnDefAttr getProducedReference(){ return getRef(); }
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

////////////////////////////////////////////////////////////////////////////////////////////////////
// Property Graph
////////////////////////////////////////////////////////////////////////////////////////////////////

// The following operations are strictly runtime-specific for the given PropertyGraph data structure 
// adding the processing of Neo4j-style graphs to LingoDB. This means they are not necessary for a 
// general graph processing IR, which is minimally complete with lowerings for CreateOp, ScanOp, 
// GatherOp and ScatterOp on node and edge sets.

def ScanPropertySetOp : Graph_Op<"subop.scan_property_set", [Pure,SubOperator,ReferenceProducer,DeclareOpInterfaceMethods<StateUsingSubOperator>]> {
    let summary = "scan state (sequentially)";
    let arguments = (ins AnyType : $prop_set, ColumnDefAttr: $ref);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{ $prop_set `:` type($prop_set) custom<CustDef>($ref) attr-dict }];
    let extraClassDeclaration = [{
        lingodb::compiler::dialect::tuples::ColumnDefAttr getProducedReference(){ return getRef(); }
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

//===----------------------------------------------------------------------===//
// Relationship filtering by type
//===----------------------------------------------------------------------===//

def CreateTypeOp : Graph_Op<"create_type", [Pure,SubOperator,ReferenceProducer]> {
    let summary = "create graph type";
    let arguments = (ins TupleStream : $stream, ColumnDefAttr:$typeRef, StrAttr:$type);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{  $stream $type `->`  custom<CustDef>($typeRef) attr-dict }];
    let extraClassDeclaration = [{
        lingodb::compiler::dialect::tuples::ColumnDefAttr getProducedReference(){ return getTypeRef(); }
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

def FilterByTypeOp : Graph_Op<"filter_by_type", [Pure,SubOperator]> {
    let summary = "filter graph ref by type";
    let arguments = (ins TupleStream : $stream, ColumnRefAttr : $ref, ColumnRefAttr : $typeRef);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{  $stream custom<CustRef>($ref) `of` `type` custom<CustRef>($typeRef) attr-dict }];
    let extraClassDeclaration = [{
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

def CastPropertyRefOp : Graph_Op<"cast_property_ref", [Pure,SubOperator]> {
    let summary = "cast to typed property ref";
    let arguments = (ins TupleStream : $stream, ColumnRefAttr : $ref, ColumnDefAttr : $typedRef);
    let results = (outs TupleStream : $res);
    let assemblyFormat = [{  $stream custom<CustRef>($ref) `->` custom<CustDef>($typedRef) attr-dict }];
    let extraClassDeclaration = [{
        mlir::Operation* cloneSubOp(mlir::OpBuilder& builder, mlir::IRMapping& mapping, lingodb::compiler::dialect::subop::ColumnMapping& columnMapping);
    }];
}

#endif // GENGODB_DIALECT_GRAPH_OPS