#ifndef LINGODB_COMPILER_CONVERSION_GRAPH_GRAPHHELPERS_H
#define LINGODB_COMPILER_CONVERSION_GRAPH_GRAPHHELPERS_H
#include <cstdint>

namespace lingodb::compiler::dialect {
namespace graph {

enum NodeEntry {
    NODE_ENTRY_IN_USE_PTR = 0,
    NODE_ENTRY_NEXT_REL_ID_PTR = 1,
    NODE_ENTRY_PROPERTY_PTR = 2,
    NODE_ENTRY_LABEL_0_PTR = 3,
    NODE_ENTRY_LABEL_1_PTR = 4,
    NODE_ENTRY_LABEL_2_PTR = 5,
    NODE_ENTRY_LABEL_3_PTR = 6,
    NODE_ENTRY_LABEL_4_PTR = 7,
    NODE_ENTRY_EXTRA_PTR = 8
};
enum RelationshipEntry {
    RELATIONSHIP_ENTRY_IN_USE_PTR = 0,
    RELATIONSHIP_ENTRY_FIRST_NODE_ID_PTR = 1,
    RELATIONSHIP_ENTRY_SECOND_NODE_ID_PTR = 2,
    RELATIONSHIP_ENTRY_RELATIONSHIP_TYPE_PTR = 3,
    RELATIONSHIP_ENTRY_FIRST_PREV_REL_ID_PTR = 4,
    RELATIONSHIP_ENTRY_FIRST_NEXT_REL_ID_PTR = 5,
    RELATIONSHIP_ENTRY_SECOND_PREV_REL_ID_PTR = 6,
    RELATIONSHIP_ENTRY_SECOND_NEXT_REL_ID_PTR = 7,
    RELATIONSHIP_ENTRY_PROPERTY_PTR = 8,
    RELATIONSHIP_ENTRY_FIRST_IN_CHAIN_MARKER_PTR = 9
};
enum PropertyEntry {
    PROPERTY_ENTRY_IN_USE_PTR = 0,
    PROPERTY_ENTRY_NEXT_PROP_ID_PTR = 1,
    PROPERTY_ENTRY_PREV_PROP_ID_PTR = 2,
    PROPERTY_ENTRY_PROPERTY_KEY_PTR = 3,
    PROPERTY_ENTRY_PROPERTY_STORAGE_TYPE_PTR = 4,
    PROPERTY_ENTRY_PROPERTY_VALUE_PTR = 5
};

} // graph
} // lingodb::compiler::dialect

#endif // LINGODB_COMPILER_CONVERSION_GRAPH_GRAPHHELPERS_H